name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  all:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: compile
      run: make
    - name: install
      run: sudo make install
    - name: codecheck
      run: ./scripts/clang_format.sh --test
