name: C/C++ CI

on:
  push:
    branches: [ master, dev, CI ]
    paths-ignore:
      - 'README*'
      - 'assets/**'
  pull_request:
    branches: [ master, dev, CI ]
    paths-ignore:
      - 'README*'
      - 'assets/**'

jobs:
  build-latest:
      runs-on: ubuntu-latest
   
      steps:
      - uses: actions/checkout@v2
      - name: compile
        run: make
      - name: install
        run: sudo make install
      - name: codecheck
        run: ./scripts/clang_format.sh --test
        
  build-14:
      runs-on: ubuntu-14.04
   
      steps:
      - uses: actions/checkout@v2
      - name: compile
        run: make
      - name: install
        run: sudo make install
      - name: codecheck
        run: ./scripts/clang_format.sh --test
