name: C/C++ CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README*'
      - 'assets/**'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README*'
      - 'assets/**'

jobs:
  build:
      strategy:
        matrix:
          os: [ubuntu-latest, ubuntu-16.04]
      runs-on: ${{ matrix.os }}
   
      steps:
      - uses: actions/checkout@v2
      - name: compile
        run: make
      - name: install
        run: sudo make install
      - name: codecheck
        run: ./scripts/clang_format.sh --test
